### ISSUE TITLE
Usage with jade causes some files to not be compiled

### ISSUE THREAD

**Issue by MikaAK** [jgable/gulp-cache#44]
I'm using gulp-cache with gulp-jade and for some reason it causes the occasional file to not be created within jade. 

The app I'm working on is getting quite large and this only started to happen recently.  Even resetting the cache doesn't make the file get created!!! 
I've tried not using a key function but that was no help, however If I remove `$.cache()` it works properly

My gulp task is as such

```javascript
gulp.task('jade', function() {
  return gulp.src('app/**/*.jade')
    .on('error', shallowError)
    .pipe($.cache($.jade({pretty: true, doctype:'html'}), {key: createKey}))
    .pipe(gulp.dest('.tmp'))
})
```
```javascript
var createKey = function(file) {
  return [file.contents.toString('utf8'), file.stat.mtime, file.stat.size].join('')
}
```

**Comment by shinnn** [comment]
> this only started to happen recently

Do you mean your `jade` task using gulp-cache *was* working well?

**Comment by MikaAK** [comment]
Correct it was working well up till recently my colleagues and I have only begun to notice this. It could also be due to an update!

**Comment by shinnn** [comment]
Could you downgrade gulp-cache to v0.2.8 and try again?

We recently published gulp-cache v0.2.9 but AFAK there is no large difference from v0.2.8.

**Comment by MikaAK** [comment]
I downgraded and tried again but I'm still getting the same problem unfortunately

**Comment by jgable** [comment]
Can we get access to your repo, or could you put together an example repo that reproduces the issue?  This helps narrow it down faster.

**Comment by shinnn** [comment]
Yes, the only difference between v0.2.9 and v0.2.8 is a version bump of [object-omit](https://github.com/jonschlinkert/object.omit) and there is no breaking change.

**Comment by jgable** [comment]
You should also have your `createKey` function key off the version of the jade plugin so that when you update the jade plugin the previously cached entries are re-run with the new version of it.

**Comment by MikaAK** [comment]
Good advice @jgable I'll implement it. Unfortunately this is happening on our repo at work so I can't give access. 
It keeps happening but randomly and after cutting saving then pasting and saving the contents of the `jade` file it no longer occurs on that specific file. When it happens to another file I'll post back and see If I can update with more info. Unfortunately I have yet to be able to reproduce this bug on purpose!

**Comment by Slayer95** [comment]
I think I have a repro case for this (no `gulp-jade` though, Might be a different issue?)

1) Clone https://github.com/Slayer95/Pokemon-Showdown/tree/gulp-cache
2) `npm install`
3) `gulp`. It should fail.
4) Comment out this line: https://github.com/Slayer95/Pokemon-Showdown/blob/gulp-cache/dev-tools/jscs-custom-rules/validate-case-indentation.js#L73
5) Run `gulp` again. It should succeed.
6) Revert step 4.
7) Run `gulp` again. It passes!
8) Run `gulp clear`.
9) Run `gulp` once more. It passes again!!

**Comment by jgable** [comment]
I'm a little busy tonight with family shenanigans and a date night. I'll
probably have some time this weekend to take a closer look. I have a
suspicion it has to do with the way the key is generated for that .js file.

**Comment by jgable** [comment]
And thank you for the detailed steps and a repro repo branch.

**Comment by Slayer95** [comment]
Any progress in this, @jgable ?
Would you like a more simplified test case?

**Comment by jgable** [comment]
I took a look this morning, but `gulp fastlint` always fails for me.  Looks like a lot of naked `if` statements without `{ ... }` around the conditional body.  Can you try running through your steps with a fresh clone, or try `npm update` to get the latest dependencies?

I tried to dig in a little deeper manually by spitting out the `keyHash` in your `key` function, and it looks like the hash of the file changes when any of those `dev-tools/**` files changes as you'd expect, which would make them run again.

The `gulpCache.clearAll` doesn't clear your `fileCache` because you're using a custom one and we have no reference to it in `clearAll`.  I could update that function to take options and allow you to pass a custom fileCache, or you could just run `fileCache.clear` on your own custom one.  When you go with a custom fileCache you kind of have to go all the way of managing it yourself.

**Comment by jgable** [comment]
Closing this since I haven't heard back in a while.
