### ISSUE TITLE
suggestion: api change / alternative

### ISSUE THREAD

**Issue by kilianc** [jgable/gulp-cache#48]
so right now I have something like:

```js
gulp.task('inline:html', function () {
  return gulp.src('dist/**/*.html')
    .pipe(plugins.cache(plugins.inlineSource({
      svgAsImage: true,
      rootpath: process.cwd() + config.root
    })))
    .pipe(gulp.dest('dist'))
})

gulp.task('minify:html', function () {
  return gulp.src('dist/**/*.html')
    .pipe(plugins.cache(plugins.minifyHtml({
      conditionals: true,
      quotes: true
    })))
    .pipe(gulp.dest('dist/'))
})
```

which in general is kinda ugly (`plugins.cache(plugins.minifyHtml({`) and it becomes even worse because you need to address the fact that those two tasks are using the same cache because running on the same files.

```js
gulp.task('inline:html', function () {
  return gulp.src('dist/**/*.html')
    .pipe(plugins.cache.start('inline'))
    .pipe(plugins.inlineSource({
      svgAsImage: true,
      rootpath: process.cwd() + config.root
    }))
    .pipe(plugins.cache.end('inline'))
    .pipe(gulp.dest('dist'))
})

gulp.task('minify:html', function () {
  return gulp.src('dist/**/*.html')
    .pipe(plugins.cache.start('minify'))
    .pipe(plugins.minifyHtml({
      conditionals: true,
      quotes: true
    }))
    .pipe(plugins.cache.end('minify'))
    .pipe(gulp.dest('dist/'))
})
```

With some magic we could control the internal flow, have better syntax, also you cloud potentially `.pipe` multiple times between start/end block.

N.B. really opinionated suggestion, feel free to tell me to STFU. :beers:

**Comment by kilianc** [comment]
my bad it appears that the cache is indexed my `file.content` :)

**Comment by jgable** [comment]
Seems interesting. Is it idiomatic in gulp to have those "checkpoints" in
the stream? Do you have some examples of other plugins that have done this
well?

**Comment by kilianc** [comment]
The only thing close to this is: https://github.com/floridoo/gulp-sourcemaps

**Comment by iliakan** [comment]
Filter/restore stream at checkpoints: https://www.npmjs.com/package/gulp-filter

**Comment by jgable** [comment]
This is still interesting but I don't have any time to implement anything like this.  If someone wants to put together a PR with this then I'd be willing to help get it pushed through.
