### ISSUE TITLE
Cannot work with streams files

### ISSUE THREAD

**Issue by iliakan** [jgable/gulp-cache#52]
In many cases file path + mtime is enough to take from cache.
Why does the plugin force to read the file? That counters performance.

`gulp.src('**/*.js', {read: false})` should be cacheable, why not?

```
file.path + file.mime -> cache?
  -> yes -> get content and all needed from cache
  -> no -> populate content and process it
```

**Comment by shinnn** [comment]
> Cannot work with streams/null files? Why?

I don't see any benefits to cache `null` vinyl objects, which are directories.

**Comment by iliakan** [comment]
You cache not the null objects. You cache the result of it's processing. The processing reads them and populates. 

```
gulp.src('**', { read: false })
  .cache( stream which reads and processes files and returns the result, { options } )
```
I really have no clue how to make it even more obvious.

**Comment by jgable** [comment]
I haven't prioritized streams because I didn't have a use case for it.  Your examples seem contrived, can you give an actual example of something you can safely cache based on file.path and file.mime alone?  Seems like the contents of those files would affect the output of any proxied task that I can think of.

**Comment by iliakan** [comment]
@jgable: most of stuff. if same file is not modified, then can take from cache, isn't that obvious? :1234: )

**Comment by shinnn** [comment]
Closing for the lack of useful feedback and impoliteness of the issue reporter.

**Comment by jgable** [comment]
This is my assertion: You cannot for certain know whether the file is the
same without checking the contents. I have asked for a situation where that
assertion could be proven wrong and your only reply is "it's obvious". This
is unproductive.

**Comment by iliakan** [comment]
Dear Sirs,

In my experience many caches rely on that assertion. Can be disabled for some rare cases, but mostly true.
I'm very sorry if my response appears impolite. I mean no offense to anyone.

The module is yours, I only tried to make it better by suggesting the optimizarion that I think is good. 

With all respect for your work in the field of open source.
--
Ilya

**Comment by jgable** [comment]
You still have not given a single concrete example of a scenario where you
could reliably cache a task based only on the file name and mime type. I
don't think you really understand the functionality of this plugin.

**Comment by iliakan** [comment]
@jgable Let's consider compilation for example. The task is to compile the file by TypeScript (CoffeeScript whatever) compiler.

Wouldn't it be sane to reuse the previous result if the same file is unchanged?

**Comment by jgable** [comment]
In order to tell whether the file has changed, you would need to look at
the contents and compare what it was before.

**Comment by sgen** [comment]
What about file.stat.mtime?

https://github.com/gulpjs/vinyl#optionsstat
https://nodejs.org/api/fs.html#fs_class_fs_stats

It contains the last time the file was modified. Store that value and if it doesnt change the next time the task is run the cached result can be used.

**Comment by jgable** [comment]
Seems plausible as a reasonable default implementation. I'm still skeptical
it'll be consistent.

Put a PR together with some tests to feel it out.

**Comment by iliakan** [comment]
You use a single cache file per original file, right?
So, if the file mtime is not newer than the cache mtime, then that's it. No need to store anything, you already have it. 

That allows to speed up things a lot. File linting, file compilations, a lot of other stuff.
