### ISSUE TITLE
Missing some file in my dist folder when using imagemin

### ISSUE THREAD

**Issue by sinedied** [jgable/gulp-cache#54]
Hello,

I use a rather classic gulp / cache / imagemin workflow:

```js
gulp.task('cordova:resources', function() {
  return gulp.src('resources/**')
    .pipe($.cache($.imagemin({
      optimizationLevel: 3,
      progressive: true,
      interlaced: true
    })))
    .pipe(gulp.dest(path.join(conf.paths.tmp, 'resources')))
    .pipe($.size());
});
```

But with this, some file are not copied to the dest folder?

When removing the $.cache(), everything works well.
If I use their file name directly instead instead of a glob, it also works (after clearing the cache)...

Any ideas?

**Comment by shinnn** [comment]
* Which OS?
* Node, npm, gulp-cache and gulp-imagemin versions?
* Create a small repository by which everyone can reproduce the problem you're running into.

======

[*How To Ask Questions The Smart Way*](http://www.catb.org/esr/faqs/smart-questions.html)

**Comment by sinedied** [comment]
I have found the source of the problem: I have images that have the same content, but a different file name, and only the first occurence of the file is output (which seems right according to default options).

But even using a custom key function like this, it still does not work:
```js
gulp.task('cordova:resources', function() {
  return gulp.src('resources/**/*.{gif,jpg,png,svg}')
    .pipe($.cache($.imagemin({
      optimizationLevel: 3,
      progressive: true,
      interlaced: true
    })), {
      key: function(file) {
        return file.contents.toString('utf8') + file.path;
      }
    })
    .pipe(gulp.dest(path.join(conf.paths.tmp, 'resources')))
    .pipe($.size());
});
```
I thought that adding the file path to generate the file key should do the trick?

BTW I use nodejs 5.0.0, npm 3.8.1, gulp-cache 0.4.2 and gulp-imagemin 2.4.0.

**Comment by sinedied** [comment]
Silly me, there was a parenthesis issue, the previous solution works (I edited the previous comment).

**Comment by shinnn** [comment]
> `return file.contents.toString('utf8') + file.path;`

Yes, we're trying include the file path to `key` by default. https://github.com/jgable/gulp-cache/issues/51#issuecomment-177869896

We'd be grateful if you could create a pull request.

**Comment by sinedied** [comment]
I'll try to wrap this change and a unit test in a PR then :)
