### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by athies** [jgable/gulp-cache#64]
When using gulp-cache I see the following warning...

(node:1655) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

**Comment by outaTiME** [comment]
+1

**Comment by jgable** [comment]
We fixed this in #63 but I guess it hasn't been deployed to NPM.

There we go, published as 0.4.6.  @shinnn I will add you as an npm owner so you can publish from now on.
