### ISSUE TITLE
gulp cache v0.5.0 doesn't work with gulp-imagemin

### ISSUE THREAD

**Issue by nurbol-sarsenbayev** [jgable/gulp-cache#68]
```
var gulp     = require('gulp'),
    imagemin = require('gulp-imagemin'),
    cache    = require('gulp-cache');

gulp.task('imagemin', function() {
	return gulp.src('app/img/**/*')
		.pipe(cache(imagemin()))
		.pipe(gulp.dest('dist/img')); 
});
```

When I run command "gulp imagemin" in terminal, it starts task, but command ends not finishing task
![gulp-cahce-error](https://user-images.githubusercontent.com/6231058/32214889-7932281c-be4a-11e7-9081-7fcc0f056ad7.JPG) 
My package.json devDependencies part looks like this:
![package-json](https://user-images.githubusercontent.com/6231058/32214995-d6913f16-be4a-11e7-9cda-fd751157182b.JPG)
However, if I use gulp-cahce version v0.4.6, it works fine.
Here source code to download:
[gulp-cahce-error.zip](https://github.com/jgable/gulp-cache/files/1430128/gulp-cahce-error.zip)

**Comment by brenopolanski** [comment]
I have the same problem...

**Comment by dangreen** [comment]
@nurbol-sarsenbayev @brenopolanski now you can try [gulp-cache@1.0.1](https://www.npmjs.com/package/gulp-cache)

**Comment by brenopolanski** [comment]
@dangreen it's working :+1:

**Comment by nurbol-sarsenbayev** [comment]
Thank you! it's working!
