### ISSUE TITLE
Bad dockumentation of Options.

### ISSUE THREAD

**Issue by puggan** [jgable/gulp-cache#71]
Got the same error as #45 and #49.

It looks like they both missread the dockumentation, on how to use the options.
So I guess I don't get the dockumentation either.

Could you please add an exemple no how to use the options.

Most other plugins use options as an optional parameter, like:
`.pipe(plug.cache({name: 'less'}, plug.less()))`

But i guess thats not the case in your plugin.

**Comment by puggan** [comment]
Wrong target

**Comment by dangreen** [comment]
Done in https://github.com/jgable/gulp-cache/pull/74
