### ISSUE TITLE
Question: single file vs wildcard

### ISSUE THREAD

**Issue by juliemturner** [jgable/gulp-cache#78]
I'm struggling with something that worked in previous versions and is no longer working:
(modified slightly for clarity)

```
gulp.src("./dist/**/*.js")
    .pipe(
       cache(
        map(function (file, cb) {
          console.log("Mapping: " + file.basename);
          cb(null, file);
        })
      )
    );
```

If there are 3 files in the dist folder with the .js extension the mapper is not called if the file hasn't changed. If I modify the code to only get a single file (there is an example in the Readme that does this) it seems like it doesn't cache or thinks the file has changed even if it hasn't.  Is there anything super obvious that I'm doing wrong?

I created this simplified example and even if test.js doesn't change it still calls my map function.

(FYI, I need the map function to make a call to a more complicated scenario, so "remove map" isn't really going to cut it, although if that's the culprit I'm open but doesn't seem to be since as I said the above example does work)

```
gulp.src("dist/test.js")
    .pipe(
      cache(
        map(function (file, cb) {
          console.log("Mapping: " + file.basename);
          cb(null, file);
        })
      )
    );
```

**Comment by dangreen** [comment]
@juliemturner 

Hi!

`gulp-cache` can work only with Transform streams, `map-stream` is simple Stream.

Instead of `map` you can use `through2`:

```js
thourgh2.obj((file, _, cb) => {
  console.log("Mapping: " + file.basename);
  cb(null, file);
})
```
