### ISSUE TITLE
How to fix ReferenceError: cache is not defined error ?

### ISSUE THREAD

**Issue by webmasterpf** [jgable/gulp-cache#82]
Hi,
I would to clear my browser cache with gulp and browser-sync but I get this error when my task is running:
`ReferenceError: cache is not defined`
 My gulpfile contain:
```
var basePaths = {
    project:  './',
    projectsourcemap:  '../',
    src: './sass/**/*.scss', // fichiers scss à surveiller
};
gulp.task('clearCache', function() {
  // Or, just call this for everything
  cache.clearAll();
});

gulp.task('default', ['browser-sync'], function(){
  gulp.watch(basePaths.src, ['sasscompil']);
  gulp.watch(basePaths.src, ['clearCache']);
});
```

Thanks for help

**Comment by dangreen** [comment]
@webmasterpf Hi. `gulp-cache` is not about browser's cache.

**Comment by webmasterpf** [comment]
Ok, does exist some gulp plugin to do so ? Because when I change an image, the browser-sync server doesn't replace it with the new one ...so I guess BS have a cache and I need to clear it as gulp do with css or js files.

**Comment by dangreen** [comment]
@webmasterpf https://www.technipages.com/google-chrome-how-to-completely-disable-cache
